"""add status

Revision ID: 54451186b76d
Revises: 
Create Date: 2022-04-12 15:58:47.142123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54451186b76d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
